[package]
name = "streamed_json"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
streamed_json_proc_macro = { path = "streamed-json-proc-macro" }
